### ISSUE TITLE
[Bug]: 7800 xt ( RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check )

### ISSUE THREAD

**Issue by Dervlex** [lshqqytiger/stable-diffusion-webui-directml#351]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Error while starting Automatic1111.
I had it run on my RX6800, but on my 7800 XT it dont want to work. I tried everything.

Yes on Linux it works, but i want to use it in windows...
Any idea ?

### Steps to reproduce the problem

1. Reinstall
2. Different pytorch versions
3. Clean Driver Install

### What should have happened?

That Automatic1111 starts.

### Sysinfo

Not possible.

### Console logs

```Shell
File "Y:\stable deiff\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "Y:\stable deiff\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "Y:\stable deiff\stable-diffusion-webui\modules\launch_utils.py", line 384, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Drücken Sie eine beliebige Taste . . .
```

**Comment by Dervlex** [comment]
> #335 Add `--use-directml`.

I tried this. Same error.
I tried also to add the "torch-directml" into the requirements.txt. but not sure if it was right.

I add it one time behind the normal "torch", deleted then the venv folder and started the web-user.bat.

This doesnt work.

After that i changed the "torch" back to normal and added the "torch-directml" on the bottom.
Worked also not.

Everytime same issue.

Any idea ?

**Comment by computerex** [comment]
Same issue on RX6600, Windows 11. 

> venv "C:\projects\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: cfa6e40e6d7e290b52940253bf705f282477b890
Traceback (most recent call last):
  File "C:\projects\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\projects\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "C:\projects\stable-diffusion-webui-directml\modules\launch_utils.py", line 560, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .

**Comment by disbox19** [comment]
add torch-direct in requirements_versions.txt
then .venv\scripts\activate
pip install -r requirements.txt
if error again
pip install httpx==0.24.1

**Comment by Drael64** [comment]
> > #335 Add `--use-directml`.
> 
> I have the same problem. It was working until I updated. Not it gives this error, and if I put in '--use-directml' it returns AttributeError: module 'torch' has no attribute 'dml'
> 
> I did a fresh install because updating broke my old copy.


> add torch-direct in requirements_versions.txt then .venv\scripts\activate pip install -r requirements.txt if error again pip install httpx==0.24.1


Does this first step need an "==" version number like the others in this file?

**Comment by disbox19** [comment]
> > > [第335章](https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/335)添加`--use-directml`。
> > 
> > 
> > 我也有同樣的問題。在我更新之前它一直有效。不會出現此錯誤，如果我輸入“--use-directml”，它會返回 AttributeError: module 'torch' has no attribute 'dml'
> > 我進行了全新安裝，因為更新破壞了我的舊副本。
> 
> > 在requirements_versions.txt中加入torch-direct，然後.venv\scripts\activate pip install -r requests.txt 如果再次出錯 pip install httpx==0.24.1
> 
> 我認為你最後漏掉了一個ml。我執行了這些建議的步驟，在參數末尾添加了 --reinstall torch (sp?) 或類似的步驟，並且全新安裝似乎有效。基本上它是建議修復的組合。如果其他人遇到此問題，他們應該查看錯誤報告以查找像這樣的最近的幾個條目，看看每個人的建議。您可能像我一樣，需要應用其中幾個才能再次識別 GPU。

sorry! i miss that.

**Comment by dykoka** [comment]
> torch-directml

did you find a solution i have the exact problem as you on the same amd

**Comment by Dervlex** [comment]
> > torch-directml
> 
> did you find a solution i have the exact problem as you on the same amd

I will answer the days. My friend has not time yet to try it. Maybe tomorrow. If i get it to work then, i will write.

**Comment by Xinterp6196** [comment]
> add torch-directml in requirements_versions.txt then .\venv\scripts\activate pip install -r requirements.txt if error again pip install httpx==0.24.1

You sir are a saint. Thank you VERY much for this fix!

**Comment by Dervlex** [comment]
Actually i tried everything....
![grafik](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/142597552/49aa9752-49d1-4e6b-993b-904f4f3960ad)
![grafik](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/142597552/9d940c7a-dc88-4b76-ac68-6a6e85824725)
![grafik](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/142597552/041f46cb-204b-4a3a-889c-8abc605b4ce9)
![grafik](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/142597552/508382a1-416f-4b25-8ef6-01a35935b87f)
![grafik](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/142597552/09a472b7-213d-42a1-a630-3b7466169ce4)

tried everything.

also the start argument: --use-directml

**Comment by Vexillen** [comment]
> Actually i tried everything.... ![grafik](https://private-user-images.githubusercontent.com/142597552/294767654-49aa9752-49d1-4e6b-993b-904f4f3960ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODE0OTMsIm5iZiI6MTcwNDY4MTE5MywicGF0aCI6Ii8xNDI1OTc1NTIvMjk0NzY3NjU0LTQ5YWE5NzUyLTQ5ZDEtNGU2Yi05OTNiLTkwNGY0ZjM5NjBhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMjMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTZkOTM2MGFlMjdmNjVlZWQ0NDg2M2EyYjU5MGNkZjEyZjFjMzU0MGJkMmE1MmRhZWUyMjZkMzk1OWY3NWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QT9J66_8LyZowwvOjXBJxt213SA0Utdh2JQkoZ36aBc) ![grafik](https://private-user-images.githubusercontent.com/142597552/294767705-9d940c7a-dc88-4b76-ac68-6a6e85824725.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODE0OTMsIm5iZiI6MTcwNDY4MTE5MywicGF0aCI6Ii8xNDI1OTc1NTIvMjk0NzY3NzA1LTlkOTQwYzdhLWRjODgtNGI3Ni1hYzY4LTZhNmU4NTgyNDcyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMjMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmI1YTdiNjViMjI4YzhhYTQ1OTE2MjM4ZDkxNTgzNDY1YTljYjAyMTQyNDk5NWYyZGNlN2FkNTY1NjdkNmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8QXmv_ZHOV7kusepkoRwk6mOjZE51m_ZnYu9SP-auYg) ![grafik](https://private-user-images.githubusercontent.com/142597552/294767743-041f46cb-204b-4a3a-889c-8abc605b4ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODE0OTMsIm5iZiI6MTcwNDY4MTE5MywicGF0aCI6Ii8xNDI1OTc1NTIvMjk0NzY3NzQzLTA0MWY0NmNiLTIwNGItNGEzYS04ODljLThhYmM2MDViNGNlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMjMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGRlNjdkZTRhYjBkNmIzOGMxZWFhNTRhMGM0YmZmNWRlYmU0NzY1MzYzOTFhYWJjNzM1ODQ1ZjhhMTQxMGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zLydYVhaaZnTMjVuMNCLwhoFMScHvmSA0qPD6prbbD4) ![grafik](https://private-user-images.githubusercontent.com/142597552/294767785-508382a1-416f-4b25-8ef6-01a35935b87f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODE0OTMsIm5iZiI6MTcwNDY4MTE5MywicGF0aCI6Ii8xNDI1OTc1NTIvMjk0NzY3Nzg1LTUwODM4MmExLTQxNmYtNGIyNS04ZWY2LTAxYTM1OTM1Yjg3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMjMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTI1YTcyZGFhZWQ1ZGRmMGExNmIzYzZiNGUxMzk4YTg0OWIwNGM2ZjJjYzc0MzllODc3MDg2YzUzMTY5Mzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7VmdTbxHCgJ_v8GkRXtb14x4F8PSYUE_7KEXyeHsjRM) ![grafik](https://private-user-images.githubusercontent.com/142597552/294767801-09a472b7-213d-42a1-a630-3b7466169ce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODE0OTMsIm5iZiI6MTcwNDY4MTE5MywicGF0aCI6Ii8xNDI1OTc1NTIvMjk0NzY3ODAxLTA5YTQ3MmI3LTIxM2QtNDJhMS1hNjMwLTNiNzQ2NjE2OWNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMjMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzI3YzI5NzMwMzM1YTI3MWIwNmNmMzBkODYwM2Q5MzMxZWFjZTE0YTVlNjk5NTcyZGE5MjA0Mzk3MmQ3N2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.390qXbKio_ZDZYG28CEdHK3OOEvOwlBOKxeGbYftRr8)
> 
> tried everything.
> 
> also the start argument: --use-directml

Hey, I was gonna open up the exact same issue. I managed to make it work by following the recommandations here, so I just wanted tell you what I did exactly. This topic helped me so I hope this'll help you. 

First part I did the same. Added Torch-directml in requirements_versions.txt
I couldn't managed to do the second part. I didn't know how to run the .\venv\scripts\activate pip install -r requirements.txt command(I'm new to this stuff). So instead I just opened up the main folder. Clicked on the file url from top. Typed Cmd. Then just did "pip install -r requirements.txt". It installed some stuff, after that it still was giving the error.
Then I edited webui-user.bat added the command line --use-directml. Ran it. Instead of the error this time, it started to install some new stuff and reinstalled the torch at the end. It worked after that. I didn't clean install or anything. 

And I don't know if it's related or not. But my stable diffusion folder is like this. "stable-diffusion-webui-directml"
In the pictures you posted yours look like this. "stable-diffusion-webui"
Are you sure you downloaded the right version?

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs

I did this one.

**Comment by Karg4** [comment]
> > tried everything.
> > also the start argument: --use-directml
> 
> Hey, I was gonna open up the exact same issue. I managed to make it work by following the recommandations here, so I just wanted tell you what I did exactly. This topic helped me so I hope this'll help you.
> 
> First of all, I don't know if it's related but I noticed that, in the pictures you posted your folder named like this. "stable-diffusion-webui" But my own stable diffusion folder is named like this. "stable-diffusion-webui-directml" I think it should be like mine. Since we use the directml, right?
> 
> Are you sure you downloaded the right version? Maybe you followed an outdated youtube tutorial or something?
> 
> https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs I did this one.
> 
> 1- First part I did the same. Added Torch-directml in requirements_versions.txt
> 
> 2- I couldn't managed to do the second part. I didn't know how to run the .\venv\scripts\activate pip install -r requirements.txt command(I'm new to this stuff). a-) So instead I just opened up the main folder. (D:\stable-diffusion-webui-directml) b-) Clicked on the file url from top. Typed Cmd. c-) Command prompt opened, then I just did "pip install -r requirements.txt". It installed some stuff, after that it still was giving the error.
> 
> 3- Then I edited webui-user.bat added the command line --use-directml. Ran it. Instead of the error this time, it started to install some new stuff and reinstalled the torch at the end.
> 
> It worked after that. I didn't do clean reinstall or anything like that.

I had to dig for my never used github password just to thank you. I have followed these steps and it all works well now. The only issue I had was that I had a new error while trying to use img2img (Not enough GPU memory available, and I fixed it by using extra commands) This is how my user bat file looks now and works for AMD system using 6650XT)

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --use-directml --medvram --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --autolaunch 

call webui.bat

**Comment by ArchAngelAries** [comment]
Followed all the fixes here and realized something changed in the way directml argument is implimented, it used to be "--backend=directml"  but now the working commandline arg for directml is "--use-directml", took me a hot second because I was telling myself I already had the command arg set, but then upon comparing word for word it was indeed changed.

**Comment by srt-jay** [comment]
> add torch-directml in requirements_versions.txt then .\venv\scripts\activate pip install -r requirements.txt if error again pip install httpx==0.24.1

THANK YOU!

**Comment by bzarky** [comment]
Having the same issue. Nobara 39, 6800xt. torch-directml installed, correct python env set with pyenv. Still getting:

Using TCMalloc: libtcmalloc_minimal.so.4
fatal: No names found, cannot describe anything.
Python 3.10.13 (main, Jan 23 2024, 18:09:57) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
Version: 1.7.0
Commit hash: d500e58a65d99bfaa9c7bb0da6c3eb5704fadf25
Launching Web UI with arguments: --no-half --use-directml
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "/home/zarky/stable-diffusion-webui-directml/launch.py", line 48, in <module>
    main()
  File "/home/zarky/stable-diffusion-webui-directml/launch.py", line 44, in main
    start()
  File "/home/zarky/stable-diffusion-webui-directml/modules/launch_utils.py", line 687, in start
    import webui
  File "/home/zarky/stable-diffusion-webui-directml/webui.py", line 13, in <module>
    initialize.imports()
  File "/home/zarky/stable-diffusion-webui-directml/modules/initialize.py", line 34, in imports
    shared_init.initialize()
  File "/home/zarky/stable-diffusion-webui-directml/modules/shared_init.py", line 26, in initialize
    dml.do_hijack()
  File "/home/zarky/stable-diffusion-webui-directml/modules/dml/__init__.py", line 74, in do_hijack
    if not torch.dml.has_float64_support(device):
AttributeError: module 'torch' has no attribute 'dml'



Do I have to be running AMD official drivers or are the open source ones okay? What am i missing here? I spent all day reinstalling python versions and SD directml

**Comment by Gutwql** [comment]
According to https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/335, add --use-directml to the settings.

Set COMMANDLINE_ARGS=--opt-sub-quad-attention --lowvram --disable-nan-check --use-directml

For Windows users with AMD CPU 7900x and AMD GPU rx6700, webui-user.bat should run perfectly.

**Comment by ZacBouh** [comment]
Followed the instructions but now got this error :
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/50382656/d2e92c6b-dc3c-4642-892c-8bab4e60babf)
Followed every step
Tried on a fresh install but still i get the same error

**Comment by lshqqytiger** [comment]
Please leave a comment to the update note or open a new discussion about ZLUDA. This issue is about DirectML and closed.

**Comment by riccorohl** [comment]
Keep in mind that the line "--use-directml" has to be next to COMMANDLINE_ARGS=, as shown below. I was having a difficult time, but I ended up piecing it together. I guess it makes sense, but someone might miss it. 

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --use-directml

call webui.bat
